require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.neomake"
require "user.cmp"
require "user.lsp"
require "user.telescope"
require "user.treesitter"
require "user.autopairs"
require "user.comment"
require "user.gitsigns"
require "user.vimwiki"
require "user.signature"
require "user.nvim-tree"
require "user.lualine"
require "user.luasnip"
require "user.floaterm"
require "user.projectionist"
---- require "user.toggleterm"
require "user.impatient"
require "user.indentline"
require "user.vim-test"
require "user.outline"
require "user.whichkey"
require "user.todo"
require "user.markdown_preview"
require "user.abbreviations"
require "user.colorscheme"
require "user.autocommands"

-- transaprent window
--vim.cmd "au ColorScheme * hi SignColumn ctermbg=none guibg=none"
--vim.cmd "au ColorScheme * hi NormalNC ctermbg=none guibg=none"
--vim.cmd "au ColorScheme * hi MsgArea ctermbg=none guibg=none"
--vim.cmd "au ColorScheme * hi Normal ctermbg=none guibg=none"
--vim.cmd "au ColorScheme * hi TelescopeBorder ctermbg=none guibg=none"
--vim.cmd "au ColorScheme * hi NvimTreeNormal ctermbg=none guibg=none"
--vim.cmd "let &fcs='eob: '"
